load("@lime_deps//:requirements.bzl", "requirement")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "app",
    srcs = ["app.py"],
    deps = [
        requirement("flask"),
    ],
)
