load("@lime_deps//:requirements.bzl", "requirement")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "config",
    srcs = glob(["*.py"]),
    deps = [
        requirement("passlib"),
    ],
)
