"""Add settings model

Revision ID: 0e4848b8fec5
Revises: d16c2ebe90cc
Create Date: 2017-06-05 14:19:11.482822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e4848b8fec5'
down_revision = 'd16c2ebe90cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=20), nullable=False),
    sa.Column('setting_type', sa.Enum('INT', 'FLOAT', 'STRING', 'BOOL', name='setting_type'), nullable=False),
    sa.Column('int_value', sa.Integer(), nullable=True),
    sa.Column('float_value', sa.Float(), nullable=True),
    sa.Column('string_value', sa.Unicode(), nullable=True),
    sa.Column('bool_value', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.object_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('object_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setting')
    # ### end Alembic commands ###
