"""Rename task ordering_link table to allow for ordering other things

Revision ID: 0f8457242543
Revises: 707bac2b6bd1
Create Date: 2017-10-30 11:29:50.547201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f8457242543'
down_revision = '707bac2b6bd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('ordering_link', 'task_ordering_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('task_ordering_link', 'ordering_link')
    # ### end Alembic commands ###
