"""Add link between tags and tasks

Revision ID: 1ba4ca96664a
Revises: 64b4ea813caa
Create Date: 2018-09-21 21:47:01.252229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ba4ca96664a'
down_revision = '64b4ea813caa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_task_link',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.object_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task.object_id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_task_link')
    # ### end Alembic commands ###
