"""Add before/after relationship for ordering tasks

Revision ID: 1dcbe7f2ce15
Revises: 0e4848b8fec5
Create Date: 2017-06-20 20:32:09.205318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dcbe7f2ce15'
down_revision = '0e4848b8fec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordering_link',
    sa.Column('before_id', sa.Integer(), nullable=True),
    sa.Column('after_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['after_id'], ['task.object_id'], ),
    sa.ForeignKeyConstraint(['before_id'], ['task.object_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordering_link')
    # ### end Alembic commands ###
