"""Add tags and tag groups

Revision ID: 2f2aa179fe54
Revises: 0f8457242543
Create Date: 2017-10-30 11:43:10.686586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f2aa179fe54'
down_revision = '0f8457242543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_group',
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(length=200), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.object_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('object_id')
    )
    op.create_table('tag',
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(length=200), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['tag_group.object_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('object_id')
    )
    op.create_table('tag_ordering_link',
    sa.Column('before_id', sa.Integer(), nullable=True),
    sa.Column('after_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['after_id'], ['tag.object_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['before_id'], ['tag.object_id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_ordering_link')
    op.drop_table('tag')
    op.drop_table('tag_group')
    # ### end Alembic commands ###
