"""Add task parents

Revision ID: 52729177a07c
Revises: d34af5cc69c2
Create Date: 2017-03-17 13:40:03.063597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52729177a07c'
down_revision = 'd34af5cc69c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'task', ['parent_id'], ['object_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'parent_id')
    # ### end Alembic commands ###
