"""Add ondelete CASCADE to ordering foreign keys

Revision ID: 58ea8596e2db
Revises: 1dcbe7f2ce15
Create Date: 2017-07-30 13:58:11.421843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58ea8596e2db'
down_revision = '1dcbe7f2ce15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ordering_link_after_id_fkey', 'ordering_link', type_='foreignkey')
    op.drop_constraint('ordering_link_before_id_fkey', 'ordering_link', type_='foreignkey')
    op.create_foreign_key('ordering_link_before_id_fkey', 'ordering_link', 'task', ['before_id'], ['object_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ordering_link', 'task', ['after_id'], ['object_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ordering_link_after_id_fkey', 'ordering_link', type_='foreignkey')
    op.drop_constraint('ordering_link_before_id_fkey', 'ordering_link', type_='foreignkey')
    op.create_foreign_key('ordering_link_before_id_fkey', 'ordering_link', 'task', ['before_id'], ['object_id'])
    op.create_foreign_key('ordering_link_after_id_fkey', 'ordering_link', 'task', ['after_id'], ['object_id'])
    # ### end Alembic commands ###
