"""Allow tags outside groups

Revision ID: 64b4ea813caa
Revises: 2f2aa179fe54
Create Date: 2018-09-19 20:53:53.119736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b4ea813caa'
down_revision = '2f2aa179fe54'
branch_labels = None
depends_on = None


def upgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column('tag', sa.Column('owner_id', sa.Integer(), nullable=True))
  op.alter_column('tag', 'group_id',
                  existing_type=sa.INTEGER(),
                  nullable=True)
  op.create_foreign_key('tag_owner_id_fk', 'tag', 'user', ['owner_id'],
                        ['object_id'], ondelete='CASCADE')
  op.create_check_constraint('has_owner_xor_group', 'tag',
                             '(group_id IS NOT NULL) <> (owner_id IS NOT NULL)')
  # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_constraint('has_owner_xor_group', 'tag', type_='foreignkey')
  op.drop_constraint('tag_owner_id_fk', 'tag', type_='foreignkey')
  op.alter_column('tag', 'group_id',
                  existing_type=sa.INTEGER(),
                  nullable=False)
  op.drop_column('tag', 'owner_id')
  # ### end Alembic commands ###
