"""Add notes field for tasks

Revision ID: 707bac2b6bd1
Revises: 58ea8596e2db
Create Date: 2017-09-10 11:31:03.741908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707bac2b6bd1'
down_revision = '58ea8596e2db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('notes', sa.UnicodeText(), nullable=True))
    op.execute(sa.table('task', sa.column('notes')).update().values(notes=''))
    op.alter_column('task', 'notes', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'notes')
    # ### end Alembic commands ###
