"""Add ON DELETE CASCADE to task parents and owners

Revision ID: d16c2ebe90cc
Revises: 52729177a07c
Create Date: 2017-05-21 14:11:15.173492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd16c2ebe90cc'
down_revision = '52729177a07c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_owner_id_fkey', 'task', type_='foreignkey')
    op.drop_constraint('task_parent_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key('task_parent_id_fkey', 'task', 'task', ['parent_id'], ['object_id'], ondelete='CASCADE')
    op.create_foreign_key('task_owner_id_fkey', 'task', 'user', ['owner_id'], ['object_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_owner_id_fkey', 'task', type_='foreignkey')
    op.drop_constraint('task_parent_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key('task_parent_id_fkey', 'task', 'task', ['parent_id'], ['object_id'])
    op.create_foreign_key('task_owner_id_fkey', 'task', 'user', ['owner_id'], ['object_id'])
    # ### end Alembic commands ###
