"""Add task model

Revision ID: ddbde5d98a3d
Revises: e8ee95e07177
Create Date: 2017-03-11 10:36:18.855980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddbde5d98a3d'
down_revision = 'e8ee95e07177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(length=200), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.object_id'], ),
    sa.PrimaryKeyConstraint('object_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
