"""Add basic user model

Revision ID: e8ee95e07177
Revises: 
Create Date: 2017-02-12 12:11:08.690611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8ee95e07177'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=200), nullable=False),
    sa.Column('email', sa.Unicode(length=200), nullable=False),
    sa.Column('password_hash', sa.Unicode(length=60), nullable=False),
    sa.PrimaryKeyConstraint('object_id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
